authors = ["Romain Monier <romain.monier@estudiants.urv.cat>",
           "Marlon Funk <marlonromanbenitofelix.funk@estudiants.urv.cat>"]
name = "GeneticAlgorithm"
version = "1.0.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphIO = "aa1b3936-2fda-51b9-ab35-c553d3a640a2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.8"
Graphs = "1.7.4"
GraphIO = "0.6.0"
StatsBase = "0.33.21"